sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jorgemcunha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorgemcunha/docker-react npm run

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react_app"
  env: "Docker-reactapp-env"
  bucket_name: "elasticbeanstalk-us-east-1-854988420401"
  bucket_path: "docker-react_app"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
