sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t jorgemcunha/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jorgemcunha/docker-react npm run